import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetServerSidePropsContext } from "next";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>testing secrets:{process.env.NEXT_PUBLIC_RANDOM_SECRET}</p>
        <button onClick={() => getMovies()}>Get Movies</button>
      </main>
    </div>
  );
};

const getMovies = async () => {
  const headers = {
    "X-RapidAPI-Key": process.env.NEXT_PUBLIC_RAPID_API_MOVIES_KEY,
    "X-RapidAPI-Host": "movie-database-alternative.p.rapidapi.com",
  };

  return "avngers";
};

export default Home;
