import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetServerSidePropsContext } from "next";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>testing secrets:{process.env.NEXT_PUBLIC_RANDOM_SECRET}</p>
      </main>
    </div>
  );
};

// export async function getServerSideProps(context: GetServerSidePropsContext) {
//   return {
//     props: {
//       secret: process.env.RANDOM_SECRET,
//     }, // will be passed to the page component as props
//   };
// }

export default Home;
